import json
S = '/tmp/claude-0/-home-user-mlb-prop-system-v7/8de98087-4781-5a10-ae09-ef74590f8116/scratchpad/stokastic/out/'
G = [
 dict(id='GAP-01', priority='P0', title='Field, ownership, duplication and payout absent from selection',
      modules=['nfl/tools/showdown_portfolio.py:18-29,736-741', 'nfl/tools/showdown_next_slate.py:395-462', 'nfl/opt/classic_portfolio.py'],
      evidence='TB@DAL 150-max: our lineups averaged 40.2 field copies (max 455); 28/150 unique. Optimizer objective is the 0.9x-optimum hit proxy (D-06).',
      missing='F1-F4 of FIELD_AND_DUPLICATION_MODEL_SPEC; payout tables; EV arm behind a flag',
      tests='IPF marginals, legality, leakage AST guard plus bypass, tie-split arithmetic, universe pricing, determinism under --reverse/--shuffle, named refusals',
      promotion='spec section 7: ownership beats FC-proportional LOSO and on 3/4 prospective slates; duplication sum ratio in [1/1.5, 1.5] and Spearman >= 0.6 per fold; EV arm >= incumbent over >= 8 contests clustered by slate, with payout tables'),
 dict(id='GAP-02', priority='P0', title='Star lower tail about 10x too thin (D-01)',
      modules=['nfl/tools/showdown_draws.py', 'nfl/tools/classic_slate_run.py:85 efficiency_worlds,133 anchor_means', 'nfl/sim/game.py'],
      evidence='Lamb P(<5 DK) 0.45% in our worlds vs 6.6% [4.0, 9.5] empirical for 20+ ppg WRs (2021-2025, 70 player-seasons). Lamb was optimal CPT in 36.8% of worlds and sat at the 50% cap everywhere.',
      missing='player-level game-to-game share and efficiency volatility drawn per world',
      tests='tail PIT on held-out 2025 replay within a predeclared margin; seeded-violation test where a fixed-share world must fail the tail check',
      promotion='tail PIT inside the margin on held-out seasons, clustered by player-season; no degradation of CRPS on the means'),
 dict(id='GAP-03', priority='P0', title='Team pass volume and QB rushing carry no QB argument (D-02, D-03)',
      modules=['nfl/tools/proj_v1.py:167 team_volume', 'nfl/tools/proj_v1.py:277-303 _combine', 'nfl/tools/proj_v1.py:1295-1298 prior', 'nfl/sim/football_points.py'],
      evidence='Daniels projected 34.6 att and 3.33 carries; his one prior start had 27 att, 8 carries (6 scrambles), 55 yds. Our P(50+ rush) was 10% vs their 38%. Our P(Egbuka 100+) was 9.2%, but 1.6% conditional on Daniels <= 27 att (the dependency exists in our worlds; the centre is wrong).',
      missing='partially pooled QB-start model for pass rate, volume and scrambles (repair program G); QB-conditioned teammate shares',
      tests='CRPS/log-score experiment on 2021-2025 starter changes, clustered by game and team; regression test that a QB swap moves club pass attempts',
      promotion='pre-registered improvement on held-out starter changes; shadow on >= 4 prospective QB-change games'),
 dict(id='GAP-04', priority='P1', title='Target shares pooled by target count; no between-game share volatility (D-04)',
      modules=['nfl/tools/proj_v1.py:277-345'],
      evidence='Lamb week-4 share 0.49 (21 targets) pulled the share to 0.314; Lamb and Pickens had equal targets in weeks 1-3 (25 each); Pickens projected 0.163.',
      missing='a share model with game-level volatility and recency/robust pooling, measured by role 2021-2025',
      tests='share-forecast log score by role, leave-one-season-out; a seeded single-outlier-week test',
      promotion='beats the pooled share on held-out seasons; included in the D-01 repair acceptance'),
 dict(id='GAP-05', priority='P1', title='No opponent adjustment in the football scoring centre; defences ignore personnel',
      modules=['nfl/sim/football_points.py:11-17', 'nfl/sim/dst.py', 'nfl/sim/game.py:318-324'],
      evidence='DAL defence EPA/play allowed +0.201, ranked 32/32 in weeks 1-4 (28.0 ppg allowed); TB centre 20.7 with no adjustment. Our P(TB win) was 19.2% vs their 24-26%. Defensive inactives (Porter, Durant, Overshown, Houston) do not move DST draws.',
      missing='opponent-adjusted centre as a pre-registered shadow arm; DST personnel effect',
      tests='football_points AST guard unchanged (no market fields); held-out 2021-2025 margin and total CRPS',
      promotion='OWNER RULING REQUIRED: NOT_MODELLED by owner instruction item 9. Escalate rather than implement.'),
 dict(id='GAP-06', priority='P1', title='Published worlds break NFL accounting (D-05)',
      modules=['nfl/tools/classic_slate_run.py efficiency_worlds', 'nfl/sim/event_consistent_worlds.py (shadow arm, commit bd895bb3)'],
      evidence='TB@DAL OFFICIAL: points < 6 x offensive TDs from the stat lines in 68 (DAL) and 65 (TB) worlds; yards without catches in 1,496/2,000 worlds.',
      missing='promotion of the event-consistent arm',
      tests='zero violations on every law in WORLD_ACCOUNTING; regression on means',
      promotion='repair-program bars (separate workstream)'),
 dict(id='GAP-07', priority='P2', title='Goal-line share computed but never consumed; TD allocation ignores per-world carries',
      modules=['nfl/tools/proj_v1.py:338-339 (gl_carry_share), :663-681 (rz_intensity)', 'nfl/tools/showdown_draws.py:111', 'nfl/sim/game.py:481-490'],
      evidence='Javonte had 11 of 12 DAL inside-5 carries (tied for the league lead); the engine uses inside-20 intensity only. In our worlds rush TDs are allocated by fixed shares, so a world with more Goodson carries does not raise his TD probability (Javonte-Goodson TD r = -0.004).',
      missing='a goal-line term (tested), and TD allocation proportional to per-world red-zone or goal-line carries',
      tests='rush-TD log score by goal-line-share bucket, 2021-2025 LOSO; identity test that sum of player TDs equals club TDs still holds exactly',
      promotion='pre-registered improvement in rush-TD log score; no loss in DK CRPS'),
 dict(id='GAP-08', priority='P2', title='Same-club WR1-WR2 correlation understated',
      modules=['nfl/sim/game.py:382-408 (share family)', 'nfl/sim/share_model.py', 'nfl/sim/validate_correlations.py'],
      evidence='Measured WR1~WR2 r = +0.17 [0.13, 0.22] (PAIR_CORRELATIONS.json); TB@DAL worlds Lamb-Pickens +0.02, Egbuka-Godwin +0.05.',
      missing='check SIM_VS_MEASURED for WR1~WR2 under the shipped share family; tune nothing, diagnose the mechanism',
      tests='validate_correlations on replayed games, block bootstrap by game',
      promotion='simulated r inside the measured 95% interval'),
 dict(id='GAP-09', priority='P2', title='No event order in worlds (first TD, drive sequencing)',
      modules=['nfl/sim/game.py:41 (special teams), docstring "no play-by-play sequencing"'],
      evidence='"P(Goodson first TD) 4.1%" cannot be computed in our worlds.',
      missing='only needed if a product question requires it; the cost is a drive-level simulator',
      tests='n/a', promotion='not proposed'),
 dict(id='GAP-10', priority='P1', title='Duplication model prices only our own lineups; level and tail miscalibrated',
      modules=['nfl/field/showdown_dupe_shadow.py', 'nfl/field/showdown_dupe_research.py'],
      evidence='B4 TB@DAL: Spearman 0.71, median 1.3 predicted vs 11.5 actual, sum ratio 0.16. The on-air lineup (Dak CPT) had 295 actual copies; no pregame number of ours exists for it.',
      missing='universe-wide pricing (R3), mixture chalk component, intervals',
      tests='spec section 8 #5; calibration by predicted-copies bin',
      promotion='spec section 7 duplication bars'),
 dict(id='GAP-11', priority='P1', title='Ownership models lose to a no-fit baseline; SC-OWN-2 candidate explodes on a punt TE',
      modules=['nfl/field/showdown_shadow_field.py', 'nfl/research/ownership/sc_own_rotation_2.py', 'nfl/field/showdown_cheap_ownership_research.py'],
      evidence='CPT MAE: BLEND 1.83, FC_ONLY 1.56, SC-OWN-2 1.80, FC-proportional 1.09. BLEND Lamb/Dak CPT 37.3/33.7 vs actual 17.1/16.4. SC-OWN-2 candidate Payne Durham FLEX 94.5% vs actual 1.3%.',
      missing='ownership_v2 with the incumbent as the prior mean and a plausibility clamp',
      tests='seeded test: a $200 near-zero-projection player cannot exceed the declared bucket maximum',
      promotion='spec section 7 ownership bars'),
 dict(id='GAP-12', priority='P2', title='Leverage and optimal frequency not reported against ownership with uncertainty',
      modules=['nfl/field/showdown_shadow_board.py'],
      evidence='This report computed optimal-frequency leverage by hand; the shadow board reports exposure minus forecast only, against the OFFICIAL (not entered) portfolio.',
      missing='OF_CPT/OF_FLEX and lev with intervals in the prelock board, for the entered portfolio',
      tests='OF reproduces CPT_BOARD.p_world_optimal_captain exactly (verified here to 4 dp)',
      promotion='descriptive only; no promotion needed, never a selection input until GAP-01'),
 dict(id='GAP-13', priority='P2', title='Two 20-max Showdown contests get identical portfolios (D-07)',
      modules=['nfl/tools/showdown_portfolio.py'], evidence='TB@DAL 196438555 and 196438556 identical (best 108.91 each).',
      missing='per-contest build (as nfl/opt/classic_portfolio.py already does)', tests='portfolios differ when contests differ', promotion='operational fix'),
 dict(id='GAP-14', priority='P2', title='Conditional and joint world queries have no tool',
      modules=['(other agent) SIMULATION_QUERY_CAPABILITY_SPEC'],
      evidence='Example computed by hand here: P(DAL by 10+ and Goodson 10+ rush and Daniels < 2 pass TD) = 26.8%.',
      missing='being implemented by another agent; not specified here', tests='see that spec', promotion='see that spec'),
 dict(id='GAP-15', priority='P1', title='Payout tables and field size not captured prelock',
      modules=['nfl/postgame/showdown_standings.py (financial UNKNOWN)'],
      evidence='Standings carry no payout; winnings and net UNKNOWN for all three TB@DAL contests; fees $82.',
      missing='capture by the networked agent (outbox request; plan section 3)', tests='PAYOUT_TABLE_ABSENT refusal', promotion='prerequisite for any EV claim'),
]
json.dump({'ARTIFACT': 'IMPLEMENTATION_GAP_BOARD', 'source_slate': 'TB@DAL 2026W5 (one slate: diagnostic)', 'priority_key': 'P0 = blocks any contest-aware or star-captain decision; P1 = material, measurable; P2 = useful, lower cost of being wrong', 'gaps': G}, open(S + 'IMPLEMENTATION_GAP_BOARD.json', 'w'), indent=1)
md = ['# Implementation gap board (from the TB@DAL video-strategy audit)', '',
      '**Priority key.**',
      '- **P0**: blocks any contest-aware or star-captain decision.',
      '- **P1**: material and measurable.',
      '- **P2**: useful, with a lower cost of being wrong.', '',
      '**Ground rules.**',
      '- Every item ships SHADOW-first.',
      '- Every test is registered with `nfl/tests/_registry.py:emit()`.',
      '- One slate promotes nothing.', '',
      '| ID | Pri | Gap | Modules | Evidence | Missing | Tests needed | Promotion criteria |', '|---|---|---|---|---|---|---|---|']
for g in G:
    md.append('| ' + ' | '.join([g['id'], g['priority'], g['title'], '<br>'.join(g['modules']), g['evidence'], g['missing'], g['tests'], g['promotion']]).replace('\n', ' ') + ' |')
md += ['', '**Escalations to the owner.**',
       '- GAP-05 would change a standing owner instruction (item 9: no opponent adjustment).',
       '- GAP-01 and GAP-15 involve money (contest EV).', '',
       '**Everything else** is decided, recorded, reversible and shadow-only.']
open(S + 'IMPLEMENTATION_GAP_BOARD.md', 'w').write('\n'.join(md) + '\n')

spec = {'ARTIFACT': 'FIELD_AND_DUPLICATION_MODEL_SPEC', 'markdown': 'FIELD_AND_DUPLICATION_MODEL_SPEC.md',
        'separation': {'football': ['nfl/sim/', 'nfl/tools/proj_v1.py', 'nfl/tools/showdown_draws.py'], 'field': ['nfl/field/'], 'meeting_point': 'nfl/tools/showdown_ev.py (new, shadow)', 'invariant': 'football never imports nfl.field (AST test)'},
        'components': {'F1': 'nfl/field/ownership_v2.py (new): incumbent FC-proportional; hierarchical MNL challenger; Dirichlet intervals',
                       'F2': 'nfl/field/field_sim.py (new) extending showdown_dupe_shadow.py (B4) + showdown_archetype_field.py: q = (1-pi) q_maxent + pi q_opt (q_opt = showdown_shadow_field.py noisy optimizer); IPF to F1 marginals; contest-class parameters',
                       'F3': 'Poisson-mixture copies D(L) over parameter draws; price any lineup in the legal universe',
                       'F4': 'tie-split payout: Prize = (1/c) sum_{k=r}^{r+c-1} P_k; payout tables required'},
        'validation_bars': {'ownership': 'beat FC-proportional on CPT MAE, FLEX MAE, STAR |bias|, smoothed log score; LOSO, then >= 3 of 4 prospective slates',
                            'duplication': {'sum_actual_over_pred': [0.667, 1.5], 'on': ['top-1000 predicted lineups', 'our lineups', 'every predicted-copies bin with >= 50 lineups'], 'spearman_min': 0.6, 'unique_share_rel_error_max': 0.5, 'copy_bin_TV_max': 0.10, 'salary_and_split_TV_max': 0.05, 'interval80_coverage': [0.7, 0.9]},
                            'ev': '>= 8 prospective contests clustered by slate; realised >= incumbent with bootstrap excluding a declared loss margin; P(top1%) calibrated; payout tables captured'},
        'tb_dal_targets': json.load(open(S + 'SUPPORT_ACTUAL_FIELD_STRUCTURE_TB_DAL.json'))['196438543'] | {'NOTE': 'one slate; shape to reproduce, not parameters to fit'}}
json.dump(spec, open(S + 'FIELD_AND_DUPLICATION_MODEL_SPEC.json', 'w'), indent=1)
print('ok')
